// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/config"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/handler"
	grpc2 "github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/handler/grpc"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/handler/grpc/interceptor"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/infra/datastore"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/infra/gorm"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/infra/idgen"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

// InitializeServer builds and returns a fully wired *grpc.Server.
// Wire generates the implementation of this function in wire_gen.go.
func InitializeServer(cfg *config.Config) (*grpc.Server, func(), error) {
	todoQueriesGateway := datastore.NewTodoReader()
	todoGetter := service.NewTodoGetter(todoQueriesGateway)
	todoCommandsGateway := datastore.NewTodoWriter()
	todoUpdater := service.NewTodoUpdater(todoQueriesGateway, todoCommandsGateway)
	todoLister := service.NewTodoLister(todoQueriesGateway)
	idGenerator := idgen.NewIDGenerator()
	todoCreator := service.NewTodoCreator(todoCommandsGateway, idGenerator)
	todoDeleter := service.NewTodoDeleter(todoQueriesGateway, todoCommandsGateway)
	validate := handler.NewValidator()
	todosServiceServer := handler.NewServer(todoGetter, todoUpdater, todoLister, todoCreator, todoDeleter, validate)
	db, cleanup, err := gorm_app.Open(cfg)
	if err != nil {
		return nil, nil, err
	}
	dbInterceptor := interceptor.NewDBInterceptor(db)
	server, cleanup2, err := grpc2.NewServer(todosServiceServer, dbInterceptor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
