package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/dataloader"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/generated"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/model"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/scalar"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/usecase/input"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.CreateTodoPayload, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, name scalar.ResourceName) (*model.DeleteTodoPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTodo - deleteTodo"))
}

// UpdateTodoStatus is the resolver for the updateTodoStatus field.
func (r *mutationResolver) UpdateTodoStatus(ctx context.Context, name scalar.ResourceName, status model.TodoStatus) (*model.UpdateTodoStatusPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateTodoStatus - updateTodoStatus"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, listName scalar.ResourceName, input *model.TodosInput) (*model.TodoConnection, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, name scalar.ResourceName) (*model.Todo, error) {
	// panic(fmt.Errorf("not implemented: Todo - todo"))
	out, err := r.TodoGetter.GetTodo(ctx, &input.GetTodoInput{Name: string(name)})
	if err != nil {
		return nil, err
	}
	return &model.Todo{
		Name:      name,
		Title:     out.Title,
		Content:   out.Content,
		Status:    model.TodoStatus(out.Status),
		DueDate:   (*scalar.Time)(out.DueDate),
		CreatedAt: scalar.Time(out.CreatedAt),
	}, nil
}

// Creator is the resolver for the creator field.
func (r *todoResolver) Creator(ctx context.Context, obj *model.Todo) (*model.User, error) {
	// Use DataLoader to batch load Creator avoiding N+1 problem
	return dataloader.For(ctx).UserLoader.Load(ctx, "creator-for-"+string(obj.Name))()
}

// TodoList is the resolver for the todoList field.
func (r *todoResolver) TodoList(ctx context.Context, obj *model.Todo) (*model.TodoList, error) {
	// Use DataLoader to batch load TodoList avoiding N+1 problem
	return dataloader.For(ctx).TodoListLoader.Load(ctx, "todolist-for-"+string(obj.Name))()
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
