package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"time"

	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/apperrors"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/domain/entity"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/dataloader"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/generated"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/mapper"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/model"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/scalar"
	usecaseinput "github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/usecase/input"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.CreateTodoPayload, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, name scalar.ResourceName) (*model.DeleteTodoPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTodo - deleteTodo"))
}

// UpdateTodoStatus is the resolver for the updateTodoStatus field.
func (r *mutationResolver) UpdateTodoStatus(ctx context.Context, name scalar.ResourceName, status model.TodoStatus) (*model.UpdateTodoStatusPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateTodoStatus - updateTodoStatus"))
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, name scalar.ResourceName, input *model.UpdateTodoInput) (*model.UpdateTodoPayload, error) {
	todoName, err := entity.ParseTodoResourceName(string(name))
	if err != nil {
		return nil, apperrors.NewInvalidParameter("invalid todo resource name", err)
	}
	if err := ensureResourceUserMatch(ctx, todoName.UserID); err != nil {
		return nil, err
	}

	if input == nil {
		return nil, apperrors.NewInvalidParameter("input is required", nil)
	}

	status, err := mapper.ToDomainTodoStatus(input.Status)
	if err != nil {
		return nil, err
	}

	var dueDate *time.Time
	if input.DueDate != nil {
		t := time.Time(*input.DueDate)
		dueDate = &t
	}

	out, err := r.TodoUpdater.UpdateTodo(ctx, &usecaseinput.UpdateTodoInput{
		Name:    string(name),
		Title:   input.Title,
		Content: input.Content,
		Status:  status,
		DueDate: dueDate,
	})
	if err != nil {
		return nil, err
	}

	return &model.UpdateTodoPayload{Todo: mapper.TodoFromOutput(out, name)}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, listName scalar.ResourceName, input *model.TodosInput) (*model.TodoConnection, error) {
	listResourceName, err := entity.ParseTodoListResourceName(string(listName))
	if err != nil {
		return nil, apperrors.NewInvalidParameter("invalid todo list resource name", err)
	}
	if err := ensureResourceUserMatch(ctx, listResourceName.UserID); err != nil {
		return nil, err
	}

	limit := 20
	offset := 0
	if input != nil {
		if input.Limit != nil {
			limit = *input.Limit
		}
		if input.Offset != nil {
			offset = *input.Offset
		}
	}

	out, err := r.TodoGetter.ListTodos(ctx, &usecaseinput.ListTodosInput{
		Parent: string(listName),
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, err
	}
	return mapper.TodoConnectionFromOutput(out, listName), nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, name scalar.ResourceName) (*model.Todo, error) {
	todoName, err := entity.ParseTodoResourceName(string(name))
	if err != nil {
		return nil, apperrors.NewInvalidParameter("invalid todo resource name", err)
	}
	if err := ensureResourceUserMatch(ctx, todoName.UserID); err != nil {
		return nil, err
	}

	out, err := r.TodoGetter.GetTodo(ctx, &usecaseinput.GetTodoInput{Name: string(name)})
	if err != nil {
		return nil, err
	}
	return mapper.TodoFromOutput(out, name), nil
}

// Creator is the resolver for the creator field.
func (r *todoResolver) Creator(ctx context.Context, obj *model.Todo) (*model.User, error) {
	// Use user resource name as the dataloader key so response name is meaningful.
	name := string(obj.Name)
	if rn, err := entity.ParseTodoResourceName(name); err == nil {
		name = fmt.Sprintf("users/%d", rn.UserID)
	}

	return dataloader.For(ctx).UserLoader.Load(ctx, name)()
}

// TodoList is the resolver for the todoList field.
func (r *todoResolver) TodoList(ctx context.Context, obj *model.Todo) (*model.TodoList, error) {
	// Use todo list resource name as the dataloader key so response name is meaningful.
	name := string(obj.Name)
	if rn, err := entity.ParseTodoResourceName(name); err == nil {
		name = fmt.Sprintf("users/%d/todo-lists/%d", rn.UserID, rn.TodoListID)
	}

	return dataloader.For(ctx).TodoListLoader.Load(ctx, name)()
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
