package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"net/http"

	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/apperrors"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/model"
	http_middleware "github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/middleware/http"
	usecaseinput "github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/usecase/input"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))
	if r.AuthLogin == nil {
		return nil, fmt.Errorf("auth login usecase is not configured")
	}

	out, err := r.AuthLogin.Login(ctx, &usecaseinput.LoginInput{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	if out.User == nil {
		return nil, fmt.Errorf("login response user is nil")
	}
	rw, ok := ctx.Value(http_middleware.ResponseWriterKey).(http.ResponseWriter)
	if !ok {
		return nil, fmt.Errorf("internal server error: missing response writer")
	}

	http.SetCookie(rw, &http.Cookie{
		Name:     "access_token",
		Value:    out.AccessToken,
		MaxAge:   3600,
		Path:     "/",
		HttpOnly: false,
		Secure:   false, // Cấu hình qua biến môi trường (true trên production)
		SameSite: http.SameSiteLaxMode,
	})

	return &model.LoginPayload{
		User: &model.User{
			ID:       int(out.User.ID.Int64()),
			Username: out.User.Username,
		},
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.LogoutPayload, error) {
	if r.AuthLogout == nil {
		return nil, fmt.Errorf("auth logout usecase is not configured")
	}

	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return nil, err
	}

	if _, err := r.AuthLogout.Logout(ctx, &usecaseinput.LogoutInput{UserID: userID.Int64()}); err != nil {
		return nil, err
	}

	rw, ok := ctx.Value(http_middleware.ResponseWriterKey).(http.ResponseWriter)
	if !ok {
		return nil, apperrors.NewInternal("internal server error: missing response writer", nil)
	}

	http_middleware.ClearAccessTokenCookie(rw)

	return &model.LogoutPayload{Success: true}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterPayload, error) {
	// panic(fmt.Errorf("not implemented: Register - register"))
	if r.AuthRegister == nil {
		return nil, fmt.Errorf("user register usecase is not configured")
	}

	out, err := r.AuthRegister.Register(ctx, &usecaseinput.RegisterInput{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.RegisterPayload{
		User: &model.User{
			ID:       int(out.User.ID.Int64()),
			Username: out.User.Username,
		},
	}, nil
}
