// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/config"
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/handler"
	grpc2 "github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/handler/grpc"
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/handler/grpc/interceptor"
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/infra/datastore"
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/infra/gorm"
	"github.com/tuannguyenandpadcojp/fresher26/nam/users/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*grpc.Server, func(), error) {
	authServiceGateway := datastore.NewUserReader()
	userLogin := service.NewLoginService(authServiceGateway)
	userLogout := service.NewUserLogoutService(authServiceGateway)
	userRegister := service.NewUserRegisterService(authServiceGateway)
	userServiceServer := handler.NewServer(userLogin, userLogout, userRegister)
	db, cleanup, err := gorm_app.Open(cfg)
	if err != nil {
		return nil, nil, err
	}
	dbInterceptor := interceptor.NewDBInterceptor(db)
	server, cleanup2, err := grpc2.NewServer(userServiceServer, dbInterceptor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
