// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/internal/domain/entity"
)

func newTodoList(db *gorm.DB, opts ...gen.DOOption) todoList {
	_todoList := todoList{}

	_todoList.todoListDo.UseDB(db, opts...)
	_todoList.todoListDo.UseModel(&entity.TodoList{})

	tableName := _todoList.todoListDo.TableName()
	_todoList.ALL = field.NewAsterisk(tableName)
	_todoList.ID = field.NewInt64(tableName, "id")
	_todoList.Name = field.NewString(tableName, "name")
	_todoList.OwnerId = field.NewInt64(tableName, "owner_id")
	_todoList.CreatedAt = field.NewTime(tableName, "created_at")
	_todoList.UpdatedAt = field.NewTime(tableName, "updated_at")

	_todoList.fillFieldMap()

	return _todoList
}

type todoList struct {
	todoListDo todoListDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	OwnerId   field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t todoList) Table(newTableName string) *todoList {
	t.todoListDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todoList) As(alias string) *todoList {
	t.todoListDo.DO = *(t.todoListDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todoList) updateTableName(table string) *todoList {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Name = field.NewString(table, "name")
	t.OwnerId = field.NewInt64(table, "owner_id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *todoList) WithContext(ctx context.Context) ITodoListDo { return t.todoListDo.WithContext(ctx) }

func (t todoList) TableName() string { return t.todoListDo.TableName() }

func (t todoList) Alias() string { return t.todoListDo.Alias() }

func (t todoList) Columns(cols ...field.Expr) gen.Columns { return t.todoListDo.Columns(cols...) }

func (t *todoList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todoList) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["owner_id"] = t.OwnerId
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t todoList) clone(db *gorm.DB) todoList {
	t.todoListDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todoList) replaceDB(db *gorm.DB) todoList {
	t.todoListDo.ReplaceDB(db)
	return t
}

type todoListDo struct{ gen.DO }

type ITodoListDo interface {
	gen.SubQuery
	Debug() ITodoListDo
	WithContext(ctx context.Context) ITodoListDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITodoListDo
	WriteDB() ITodoListDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITodoListDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITodoListDo
	Not(conds ...gen.Condition) ITodoListDo
	Or(conds ...gen.Condition) ITodoListDo
	Select(conds ...field.Expr) ITodoListDo
	Where(conds ...gen.Condition) ITodoListDo
	Order(conds ...field.Expr) ITodoListDo
	Distinct(cols ...field.Expr) ITodoListDo
	Omit(cols ...field.Expr) ITodoListDo
	Join(table schema.Tabler, on ...field.Expr) ITodoListDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITodoListDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITodoListDo
	Group(cols ...field.Expr) ITodoListDo
	Having(conds ...gen.Condition) ITodoListDo
	Limit(limit int) ITodoListDo
	Offset(offset int) ITodoListDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoListDo
	Unscoped() ITodoListDo
	Create(values ...*entity.TodoList) error
	CreateInBatches(values []*entity.TodoList, batchSize int) error
	Save(values ...*entity.TodoList) error
	First() (*entity.TodoList, error)
	Take() (*entity.TodoList, error)
	Last() (*entity.TodoList, error)
	Find() ([]*entity.TodoList, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.TodoList, err error)
	FindInBatches(result *[]*entity.TodoList, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.TodoList) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITodoListDo
	Assign(attrs ...field.AssignExpr) ITodoListDo
	Joins(fields ...field.RelationField) ITodoListDo
	Preload(fields ...field.RelationField) ITodoListDo
	FirstOrInit() (*entity.TodoList, error)
	FirstOrCreate() (*entity.TodoList, error)
	FindByPage(offset int, limit int) (result []*entity.TodoList, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITodoListDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t todoListDo) Debug() ITodoListDo {
	return t.withDO(t.DO.Debug())
}

func (t todoListDo) WithContext(ctx context.Context) ITodoListDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t todoListDo) ReadDB() ITodoListDo {
	return t.Clauses(dbresolver.Read)
}

func (t todoListDo) WriteDB() ITodoListDo {
	return t.Clauses(dbresolver.Write)
}

func (t todoListDo) Session(config *gorm.Session) ITodoListDo {
	return t.withDO(t.DO.Session(config))
}

func (t todoListDo) Clauses(conds ...clause.Expression) ITodoListDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t todoListDo) Returning(value interface{}, columns ...string) ITodoListDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t todoListDo) Not(conds ...gen.Condition) ITodoListDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t todoListDo) Or(conds ...gen.Condition) ITodoListDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t todoListDo) Select(conds ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t todoListDo) Where(conds ...gen.Condition) ITodoListDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t todoListDo) Order(conds ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t todoListDo) Distinct(cols ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t todoListDo) Omit(cols ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t todoListDo) Join(table schema.Tabler, on ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t todoListDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t todoListDo) RightJoin(table schema.Tabler, on ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t todoListDo) Group(cols ...field.Expr) ITodoListDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t todoListDo) Having(conds ...gen.Condition) ITodoListDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t todoListDo) Limit(limit int) ITodoListDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t todoListDo) Offset(offset int) ITodoListDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t todoListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoListDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t todoListDo) Unscoped() ITodoListDo {
	return t.withDO(t.DO.Unscoped())
}

func (t todoListDo) Create(values ...*entity.TodoList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t todoListDo) CreateInBatches(values []*entity.TodoList, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t todoListDo) Save(values ...*entity.TodoList) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t todoListDo) First() (*entity.TodoList, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.TodoList), nil
	}
}

func (t todoListDo) Take() (*entity.TodoList, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.TodoList), nil
	}
}

func (t todoListDo) Last() (*entity.TodoList, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.TodoList), nil
	}
}

func (t todoListDo) Find() ([]*entity.TodoList, error) {
	result, err := t.DO.Find()
	return result.([]*entity.TodoList), err
}

func (t todoListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.TodoList, err error) {
	buf := make([]*entity.TodoList, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t todoListDo) FindInBatches(result *[]*entity.TodoList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t todoListDo) Attrs(attrs ...field.AssignExpr) ITodoListDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t todoListDo) Assign(attrs ...field.AssignExpr) ITodoListDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t todoListDo) Joins(fields ...field.RelationField) ITodoListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t todoListDo) Preload(fields ...field.RelationField) ITodoListDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t todoListDo) FirstOrInit() (*entity.TodoList, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.TodoList), nil
	}
}

func (t todoListDo) FirstOrCreate() (*entity.TodoList, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.TodoList), nil
	}
}

func (t todoListDo) FindByPage(offset int, limit int) (result []*entity.TodoList, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t todoListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t todoListDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t todoListDo) Delete(models ...*entity.TodoList) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *todoListDo) withDO(do gen.Dao) *todoListDo {
	t.DO = *do.(*gen.DO)
	return t
}
