// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/google/wire"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/dataloader"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/directive"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/generated"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/infra/grpc_client"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/service"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/usecase"
	"github.com/tuannguyenandpadcojp/fresher26/nam/todos/proto/todo/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"net/http"
	"os"
)

// Injectors from wire.go:

// InitializeServer builds and returns a fully wired GraphQL HTTP handler.
func InitializeServer() (http.Handler, func(), error) {
	clientConn, cleanup, err := NewTodosGRPCConn()
	if err != nil {
		return nil, nil, err
	}
	todosServiceClient := NewTodosServiceClient(clientConn)
	todoServiceGateway := grpc_client.NewTodoServiceClient(todosServiceClient)
	todoGetter := service.NewTodoService(todoServiceGateway)
	resolver := NewResolver(todoGetter)
	executableSchema := NewExecutableSchema(resolver)
	server := NewGraphQLServer(executableSchema)
	handler := NewHTTPHandler(server)
	return handler, func() {
		cleanup()
	}, nil
}

// wire.go:

var appSet = wire.NewSet(
	NewTodosGRPCConn,
	NewTodosServiceClient, grpc_client.NewTodoServiceClient, service.NewTodoService, NewResolver,
	NewExecutableSchema,
	NewGraphQLServer,
	NewHTTPHandler,
)

func NewTodosGRPCConn() (*grpc.ClientConn, func(), error) {
	target := os.Getenv("TODOS_GRPC_ADDR")
	if target == "" {
		target = os.Getenv("TODOS_SERVICE_ADDR")
	}
	if target == "" {
		target = "localhost:50051"
	}

	conn, err := grpc.NewClient(
		target, grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		_ = conn.Close()
	}

	return conn, cleanup, nil
}

func NewTodosServiceClient(conn *grpc.ClientConn) todov1.TodosServiceClient {
	return todov1.NewTodosServiceClient(conn)
}

func NewResolver(todoGetter usecase.TodoGetter) *graph.Resolver {
	return &graph.Resolver{TodoGetter: todoGetter}
}

func NewExecutableSchema(resolver *graph.Resolver) graphql.ExecutableSchema {
	cfg := generated.Config{Resolvers: resolver}
	cfg.Directives.HasPermission = directive.HasPermission()
	cfg.Directives.ValidateInput = passthroughValidationDirective

	return generated.NewExecutableSchema(cfg)
}

func passthroughValidationDirective(ctx context.Context, obj any, next graphql.Resolver) (any, error) {
	return next(ctx)
}

func NewGraphQLServer(schema graphql.ExecutableSchema) *handler.Server {
	return handler.NewDefaultServer(schema)
}

func NewHTTPHandler(server *handler.Server) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := dataloader.WithLoaders(r.Context(), dataloader.NewLoaders())
		server.ServeHTTP(w, r.WithContext(ctx))
	})
}
