// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/tuannguyenandpadcojp/fresher26/nam/todos-bff/internal/handler/graph/scalar"
)

type CreateTodoInput struct {
	ListName scalar.ResourceName `json:"listName"`
	Title    string              `json:"title"`
	Content  *string             `json:"content,omitempty"`
	Status   *TodoStatus         `json:"status,omitempty"`
	DueDate  *scalar.Time        `json:"dueDate,omitempty"`
}

type CreateTodoPayload struct {
	Todo *Todo `json:"todo"`
}

type DeleteTodoPayload struct {
	Success bool `json:"success"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Todo struct {
	Name      scalar.ResourceName `json:"name"`
	Title     string              `json:"title"`
	Content   string              `json:"content"`
	Status    TodoStatus          `json:"status"`
	DueDate   *scalar.Time        `json:"dueDate,omitempty"`
	CreatedAt scalar.Time         `json:"createdAt"`
	Creator   *User               `json:"creator,omitempty"`
	TodoList  *TodoList           `json:"todoList,omitempty"`
}

type TodoConnection struct {
	Edges    []*TodoEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TodoEdge struct {
	Node   *Todo  `json:"node"`
	Cursor string `json:"cursor"`
}

type TodoList struct {
	Name  scalar.ResourceName `json:"name"`
	Title string              `json:"title"`
}

type TodoTag struct {
	Name        scalar.ResourceName `json:"name"`
	DisplayName string              `json:"displayName"`
}

type TodosInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type UpdateTodoStatusPayload struct {
	Todo *Todo `json:"todo"`
}

type User struct {
	Name        scalar.ResourceName `json:"name"`
	DisplayName string              `json:"displayName"`
}

type Permission string

const (
	PermissionTodoDelete Permission = "TODO_DELETE"
)

var AllPermission = []Permission{
	PermissionTodoDelete,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionTodoDelete:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Permission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Permission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TodoStatus string

const (
	TodoStatusTodoStatusUnspecified TodoStatus = "TODO_STATUS_UNSPECIFIED"
	TodoStatusTodoStatusTodo        TodoStatus = "TODO_STATUS_TODO"
	TodoStatusTodoStatusInProgress  TodoStatus = "TODO_STATUS_IN_PROGRESS"
	TodoStatusTodoStatusDone        TodoStatus = "TODO_STATUS_DONE"
)

var AllTodoStatus = []TodoStatus{
	TodoStatusTodoStatusUnspecified,
	TodoStatusTodoStatusTodo,
	TodoStatusTodoStatusInProgress,
	TodoStatusTodoStatusDone,
}

func (e TodoStatus) IsValid() bool {
	switch e {
	case TodoStatusTodoStatusUnspecified, TodoStatusTodoStatusTodo, TodoStatusTodoStatusInProgress, TodoStatusTodoStatusDone:
		return true
	}
	return false
}

func (e TodoStatus) String() string {
	return string(e)
}

func (e *TodoStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoStatus", str)
	}
	return nil
}

func (e TodoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TodoStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TodoStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
